<a href="https://colab.research.google.com/github/vnkn17/AM216_Work/blob/master/AM_216_PSET_3_Problem_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Problem Set 3

## By Varun Krishnan

## Problem 1


In [0]:
### Problem Specification: 


### Import Statements

In [0]:
import subprocess
import sys

def install(package):
    subprocess.call([sys.executable, "-m", "pip", "install", package])


In [0]:
install("tensorflow>=1.7.0")
install('tensorflow-hub')

In [0]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import scipy.optimize as spopt
import tensorflow_hub as hub


W0305 22:25:26.358505 140330784204672 __init__.py:56] Some hub symbols are not available because TensorFlow version is less than 1.14


In [0]:
from __future__ import print_function

import datetime
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K

Using TensorFlow backend.


In [0]:
### Loading Data

In [0]:
import zipfile
with zipfile.ZipFile("square_T1.zip","r") as zip_ref1:
    zip_ref1.extractall("square_T1")
with zipfile.ZipFile("square_T2.zip","r") as zip_ref2:
    zip_ref2.extractall("square_T2")
with zipfile.ZipFile("square_T3.zip","r") as zip_ref3:
    zip_ref3.extractall("square_T3")
with zipfile.ZipFile("square_T4.zip","r") as zip_ref4:
    zip_ref4.extractall("square_T4")
import zipfile
with zipfile.ZipFile("triangle_T1.zip","r") as zip_ref5:
    zip_ref5.extractall("triangle_T1")
with zipfile.ZipFile("triangle_T2.zip","r") as zip_ref6:
    zip_ref6.extractall("triangle_T2")
with zipfile.ZipFile("triangle_T3.zip","r") as zip_ref7:
    zip_ref7.extractall("triangle_T3")
with zipfile.ZipFile("triangle_T4.zip","r") as zip_ref8:
    zip_ref8.extractall("triangle_T4")
with zipfile.ZipFile("square_10T.zip","r") as zip_ref9:
    zip_ref9.extractall("square_10T")
with zipfile.ZipFile("triangle_10T.zip","r") as zip_ref10:
    zip_ref10.extractall("triangle_10T")

In [0]:
import zipfile
square_T1 = []
square_T2 = []
square_T3 = []
square_T4 = []

for i in range(250):
    square_T1.append(np.loadtxt('./square_T1/square_T1/'+str(i).zfill(3), delimiter=',')) ## Change to your local directory!
    square_T2.append(np.loadtxt('./square_T2/square_T2/'+str(i).zfill(3), delimiter=',')) ## Change to your local directory!
    square_T3.append(np.loadtxt('./square_T3/square_T3/'+str(i).zfill(3), delimiter=',')) ## Change to your local directory!
    square_T4.append(np.loadtxt('./square_T4/square_T4/'+str(i).zfill(3), delimiter=',')) ## Change to your local directory!

print(len(square_T1[0]))

32


In [0]:
# Code to handle each of the 10 configurations of each of the Test Versions of the squares and triangles, respectively.

In [0]:
for k in range(10):
    globals()['test_square' + str(k)] = []
    globals()['test_triangle' + str(k)] = []

In [0]:
test_square = []
test_triangle = []
for k in range(10):
    for i in range(10):
        globals()['test_square' + str(k)].append(np.loadtxt('./square_10T/square_10T/T'+str(k).zfill(2) + "#" + str(i).zfill(2), delimiter=',')) ## Change to your local directory!
        globals()['test_triangle' + str(k)].append(np.loadtxt('./triangle_10T/triangle_10T/T'+str(k).zfill(2) + "#" + str(i).zfill(2), delimiter=',')) ## Change to your local directory!


In [0]:
len(test_square2)

10

In [0]:
len(test_triangle0)

10

## Part A: 
### Retrain your SVM (SVC) to train the classication model on both datasets to classify the 4 temperature classes.

This is a two part problem - we need to do this for both the square and triangular lattices.
First, this is demonstrated for the Square Lattices below:

In [0]:
data_img = np.concatenate((square_T1,square_T2,square_T3,square_T4))
data_img = data_img.reshape((-1, 32*32))
a = np.empty(len(square_T1))
a.fill(3)
b = np.empty(len(square_T2))
b.fill(2)
c = np.empty(len(square_T3))
c.fill(1)
d = np.empty(len(square_T4))
d.fill(0)
data_label = np.concatenate((a,b,c,d))

In [0]:
len(data_img[0])

1024

In [0]:
# Don't Set Random State to 0
from sklearn.model_selection import train_test_split
train_img, test_img, train_lbl, test_lbl = train_test_split(
    data_img, data_label, test_size= 0.2, random_state = 10)

In [0]:
from sklearn.svm import SVC
#clf = SVC(gamma=1/2048)
clf = SVC(C=1000,kernel='rbf',gamma=1/2048,cache_size=8000,probability=False)
clf.fit(train_img, train_lbl)
score = clf.score(test_img, test_lbl)
print(score)

0.645


In [0]:
dec1 = clf.decision_function(data_img)
print(dec1[:5])

[[-0.19757522  0.97483273  2.01309919  3.2096433 ]
 [-0.2769852   0.96655077  2.15646598  3.15396846]
 [-0.21968128  0.94532468  2.06174205  3.21261454]
 [-0.23227257  0.94980655  2.07285374  3.20961228]
 [-0.48670659  0.91741087  2.24740417  3.32189155]]


In [0]:
for k in range(10):
    print(np.mean(globals()['test_triangle' + str(k)]))
    

-0.0181640625
0.0236328125
0.0212890625
0.0673828125
-0.0140625
0.0171875
0.016796875
-0.05
-0.0142578125
-0.0703125


In [0]:
test_square1_np = np.array(test_square1)
test_square1_reshaped = test_square1_np.reshape((-1, 32*32))

In [0]:
dec[:5]

array([[ 2.09463131,  3.31623486,  0.97715298, -0.38801916],
       [ 1.9709247 ,  3.25033448,  1.04171918, -0.26297837],
       [ 2.03074118,  3.31715569,  1.00647557, -0.35437245],
       [ 2.06032578,  3.19129267,  0.95334557, -0.20496402],
       [ 1.98137599,  3.19573642,  1.11899252, -0.29610492]])

In [0]:
dec = (clf.decision_function(test_square1_reshaped))
average = 0
for k in dec:
    print(k)
    if(k >= 1):
        average = average + 10
    else:
        average = average + 0.4
print(average/len(arr))

[ 2.09463131  3.31623486  0.97715298 -0.38801916]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## Part B: 
### Train a fully connected neural network to do the classication, on both datasets.

In [0]:
from sklearn.neural_network import MLPClassifier
clf1 = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(1000,100), random_state=1)
clf1.fit(train_img, train_lbl)
score = clf1.score(test_img, test_lbl)
print(score)

0.46


## Part C:
### Train a convolutional neural network to do the classication, on both datasets. Make a table of your performance numbers for these three different models and upload these numbers.

In [0]:
from keras.utils import np_utils
train_img = train_img.reshape(800,32,32,1)
test_img = test_img.reshape(200,32,32,1)
train_lbl = np_utils.to_categorical(train_lbl)

test_lbl = np_utils.to_categorical(test_lbl)

In [0]:
import keras
model1 = Sequential()
model1.add(Conv2D(32, kernel_size = 3, input_shape=(32,32,1)))
model1.add(MaxPooling2D(pool_size=(2, 2)))

model1.add(Flatten())
model1.add(Dense(4))
model1.compile(optimizer = sgd, loss='categorical_crossentropy',metrics = ['accuracy'])

history = model1.fit(train_img,train_lbl, epochs=15, batch_size=32, verbose=2, validation_split=0.2)

Train on 640 samples, validate on 160 samples
Epoch 1/15
 - 1s - loss: 5.5674 - acc: 0.4219 - val_loss: 4.4799 - val_acc: 0.2687
Epoch 2/15
 - 0s - loss: 6.0921 - acc: 0.3359 - val_loss: 8.4473 - val_acc: 0.2562
Epoch 3/15
 - 0s - loss: 8.2927 - acc: 0.2547 - val_loss: 8.3447 - val_acc: 0.2625
Epoch 4/15
 - 0s - loss: 7.8824 - acc: 0.2406 - val_loss: 8.2718 - val_acc: 0.2625
Epoch 5/15
 - 0s - loss: 7.8362 - acc: 0.2406 - val_loss: 8.2608 - val_acc: 0.2625
Epoch 6/15
 - 0s - loss: 7.8325 - acc: 0.2406 - val_loss: 8.2605 - val_acc: 0.2625
Epoch 7/15
 - 0s - loss: 7.8324 - acc: 0.2406 - val_loss: 8.2605 - val_acc: 0.2625
Epoch 8/15
 - 0s - loss: 7.8324 - acc: 0.2406 - val_loss: 8.2605 - val_acc: 0.2625
Epoch 9/15
 - 0s - loss: 7.8324 - acc: 0.2406 - val_loss: 8.2605 - val_acc: 0.2625
Epoch 10/15
 - 0s - loss: 7.8324 - acc: 0.2406 - val_loss: 8.2605 - val_acc: 0.2625
Epoch 11/15
 - 0s - loss: 7.8324 - acc: 0.2406 - val_loss: 8.2605 - val_acc: 0.2625
Epoch 12/15
 - 0s - loss: 7.8324 - acc:

In [0]:
score = model1.evaluate(test_img, test_lbl)
print(score)

200/200 [==============================] - 0s 527us/step
[8.623410949707031, 0.27]


In [0]:
len(data_img[0])

1024

In [0]:
from keras.layers import Dense, Flatten
from keras.layers import Conv2D, MaxPooling2D

model = Sequential()

model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 1)))
model.add(Conv2D(32, (3, 3), activation='relu'))

model.add(Flatten())
model.add(Dense(4, activation='relu'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer=sgd)

history = model.fit(train_img,train_lbl, epochs=5, batch_size=32, verbose=2, validation_split=0.2)

Train on 640 samples, validate on 160 samples
Epoch 1/5
 - 7s - loss: nan - acc: 0.2422 - val_loss: nan - val_acc: 0.2500
Epoch 2/5
 - 5s - loss: nan - acc: 0.2453 - val_loss: nan - val_acc: 0.2500
Epoch 3/5
 - 4s - loss: nan - acc: 0.2453 - val_loss: nan - val_acc: 0.2500
Epoch 4/5
 - 3s - loss: nan - acc: 0.2453 - val_loss: nan - val_acc: 0.2500
Epoch 5/5
 - 2s - loss: nan - acc: 0.2453 - val_loss: nan - val_acc: 0.2500


In [0]:
history

## Part D:
### We have provided a test set of 10 spins configurations for each of the two problems. Each of the spin configurations is not necessarily at the temperatures of the training sets. Calculate your best estimate of the termperatures of these spin configurations. Upload your results to Kaggle.

## Part E: Transfer Learning


In [0]:
# define two groups of layers: feature (convolutions) and classification (dense)

feature_layers = [
    Conv2D(filters, kernel_size,
           padding='valid',
           input_shape=input_shape),
    Activation('relu'),
    Conv2D(filters, kernel_size),
    Activation('relu'),
    MaxPooling2D(pool_size=pool_size),
    Dropout(0.25),
    Flatten(),
]

classification_layers = [
    Dense(128),
    Activation('relu'),
    Dropout(0.5),
    Dense(num_classes),
    Activation('softmax')
]

# create complete model
model = Sequential(feature_layers + classification_layers)


NameError: name 'filters' is not defined

# Problem 2: Inception

## Part 1: 
### Show that the square lattice data can be trained per-fectly with inception.

In [0]:
# Inception Algorithm:
module = hub.Module("https://tfhub.dev/google/imagenet/inception_v3/feature_vector/1")
height, width = hub.get_expected_image_size(module)
images = square_T1  # A batch of images with shape [batch_size, height, width, 3].
features = module(images)  # Features with shape [batch_size, num_features].


NameError: name 'hub' is not defined

## Part 2:


## 2a)
### Train the data in "fluid org" with inception. Note that Inception takes pictures with 299 x 299 pixels. Shown that these images can be classified into different Ra nicely with inception. (You might find the python package PIL to be helpful here.)

In [0]:
## 2b)
